### ISSUE TITLE
[Suggestion for Other Addons] Compat. with other mods besides Twilight Forest.

### ISSUE THREAD

**Issue by MagmaSlime123** [KreloX/SpartanTwilight#1]
Title.

(I know I'm putting this in the wrong place, sorry if I shouldn't put this here.)

It would be nice if a compat. addon was made for The Betweenlands, EpicFight Mod, and BaseMetals/ModernMetals.

Addons do technically exist for said mods, but most if not all said addons are basically dead and haven't been updated. (Some were last updated in 2018, 2019 or very early 2020. Spartan Weaponry BaseMetals is also kind of pointless since it basically adds duplicates of Spartan's Metal weapons which can't be hidden without all weapons from the base mod or addons (Such as this one) being hidden.

**Comment by KreloX** [comment]
Maybe one day I'll update them but now I have to update this mod to 1.16.

**Comment by MagmaSlime123** [comment]
> Maybe one day I'll update them but now I have to update this mod to 1.16.

Alright. Was just wondering.
