### ISSUE TITLE
[1.12.2] Question - Material damage

### ISSUE THREAD

**Issue by giova-01** [KreloX/SpartanTwilight#2]
I dont know where to put this, but i guess github is ok. Aaand sorry for my bad English :P
Is there a way to modify how much damage each material does? it would be great to have a config for that. I dont think steeleaf-based weapons should do the same damage as diamond-based weapons. 

Thanks for the mod!

**Comment by KreloX** [comment]
Implemented in version 1.2.0 for 1.12.2
